---
abstract: 'JIS X 0213 encodings'
author:
  - 'Hatuka*nezumi - IKEDA Soji <hatuka@nezumi.nu>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Encode-JISX0213
no_index:
  directory:
    - t
    - inc
requires:
  Encode::ISO2022: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://hatuka.nezumi.nu/repos/Encode-JISX0213/
version: 0.000_06
